"""Add idempotency_key to expenses

Revision ID: 7c2cd92347ab
Revises: 20260420_0003
Create Date: 2026-04-20 23:33:42.183807

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7c2cd92347ab'
down_revision = '20260420_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uix_user_id_idempotency_key', 'expenses', ['user_id', 'idempotency_key'])
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_constraint('uix_user_id_idempotency_key', 'expenses', type_='unique')
    op.drop_column('expenses', 'idempotency_key')
    # ### end Alembic commands ###

